### ISSUE TITLE
bug when reading cdkey

### ISSUE THREAD

**Issue by ghost** [Chomenor/ioq3_new_filesystem#1]
running win64 beta5 build, the key gets saved to baseq3/q3key but everytime i start the game it keeps asking for it. tested also with latest ioq3 test build and it works fine.

**Comment by Chomenor** [comment]
Thanks for the report. I made some changes and updated the test build; let me know if it solves the problem.

**Comment by ghost** [comment]
Tested quickly and seems to be working now. Admire the effort you have put into this.

**Comment by Chomenor** [comment]
Thanks! Let me know if you find any other issues.
